import 'package:provider/provider.dart';
import 'language_service.dart';

class LocalizationService {
  static String translate(String key, String language) {
    final translations = {
      'en': {
        'filter_by_theme': 'Filter by Theme',
        'filter_by_speaker': 'Filter by Speaker',
        'filter_by_star': 'Filter by Stars',
        'filter_by_chapter': 'Filter by Chapter',
        'filter_by_shlok_number': 'Filter by Shlok Number',
        'clear': 'Clear',
        'apply': 'Apply',
        'cancel': 'Cancel',
        'showing_results': 'Showing {count} results',
        'bookmark': 'Bookmark',
        'bookmarked': 'Bookmarked',
        'search': 'Search...',
        'theme': 'Theme',
        'speaker': 'Speaker',
        'star': 'Star',
        'stars': 'Stars',
        'chapter': 'Chapter',
        'verses': 'Verses',
        'keywords': 'Keywords',
        'summary': 'Summary',
        'bookmark_text': 'Bookmark',
        'saved_bookmarks': 'Saved Bookmarks',
        'no_bookmarks': 'No bookmarks yet',
        'filters': 'Filters',
        'clear_filters': 'Clear Filters',
        'gamification_title': 'Rewards',
        'activity_header': 'VitaGita Activity',
        'points_header': 'Points',
        'your_points': 'Your Points',
        'activity_login': 'Login',
        'activity_search': 'Shlok Search',
        'activity_listen': 'Shlok Listen',
        'activity_share': 'Share',
        'levels_header': 'Levels',
        'cumulative_points': 'Cumulative Points',
        'level': 'Level',
        'level_shishu': 'Shishu',
        'level_sainik': 'Sainik',
        'level_rathi': 'Rathi',
        'level_atirathi': 'Atirathi',
        'level_maharathi': 'Maharathi',
      },
      'hi': {
        'filter_by_theme': 'विषय द्वारा फ़िल्टर करें',
        'filter_by_speaker': 'वक्ता द्वारा फ़िल्टर करें',
        'filter_by_star': 'तारों द्वारा फ़िल्टर करें',
        'filter_by_chapter': 'अध्याय द्वारा फ़िल्टर करें',
        'filter_by_shlok_number': 'श्लोक संख्या द्वारा फ़िल्टर करें',
        'clear': 'साफ़ करें',
        'apply': 'लागू करें',
        'cancel': 'रद्द करें',
        'showing_results': '{count} परिणाम दिखा रहे हैं',
        'bookmark': 'बुकमार्क',
        'bookmarked': 'बुकमार्क किया गया',
        'search': 'खोजें...',
        'theme': 'विषय',
        'speaker': 'वक्ता',
        'star': 'तारा',
        'stars': 'श्रेणी',
        'chapter': 'अध्याय',
        'verses': 'श्लोक',
        'keywords': 'कीवर्ड',
        'summary': 'सारांश',
        'bookmark_text': 'बुकमार्क',
        'saved_bookmarks': 'सहेजे गए बुकमार्क',
        'no_bookmarks': 'अभी तक कोई बुकमार्क नहीं',
        'filters': 'फ़िल्टर',
        'clear_filters': 'फ़िल्टर साफ़ करें',
        'gamification_title': 'इनाम',
        'activity_header': 'विटागीता गतिविधि',
        'points_header': 'अंक',
        'your_points': 'आपके अंक',
        'activity_login': 'लॉगिन',
        'activity_search': 'श्लोक खोज',
        'activity_listen': 'श्लोक सुनना',
        'activity_share': 'साझा करें',
        'levels_header': 'स्तर',
        'cumulative_points': 'संचयी अंक',
        'level': 'स्तर',
        'level_shishu': 'शिशु',
        'level_sainik': 'सैनिक',
        'level_rathi': 'रथी',
        'level_atirathi': 'अतिरथी',
        'level_maharathi': 'महारथी',
        'logout': 'लॉगआउट',
        'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
        'delete_account': 'खाता हटाएं',
        'delete_confirm':
            'क्या आप वाकई अपना खाता हटाना चाहते हैं? यह कार्रवाई को पूर्ववत नहीं किया जा सकता।',
        'delete': 'हटाएं',
        'not_found': 'नहीं मिला',
        'no_media': 'कोई मीडिया उपलब्ध नहीं',
      }
    };

    final lang = language == 'hi' ? 'hi' : 'en';
    return translations[lang]?[key] ?? key;
  }
}
